### ISSUE TITLE
Buggy model gets mangled by pipeline

### ISSUE THREAD

**Issue by JoshuaStorm** [AnalyticalGraphicsInc/gltf-pipeline#103]
While testing my own branch, I have found a model that is mangled in my branch as well as master:

Quickly commenting out each step and seeing the results seems to show that the model is getting mangled by the `combinePrimitives` step.

[buggy.gltf.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/326569/buggy.gltf.zip)

![goodbuggy](https://cloud.githubusercontent.com/assets/12414183/16245842/b88b5530-37d0-11e6-8b01-08f364b12ed5.jpg)
![mangledbuggy](https://cloud.githubusercontent.com/assets/12414183/16245852/bcf89132-37d0-11e6-9b8c-c3e990e5cded.jpg)

**Comment by lasalvavida** [comment]
Closed by #162.
