### ISSUE TITLE
Undefined variable "czm_sunDirectionEC"

### ISSUE THREAD

**Issue by javagl** [AnalyticalGraphicsInc/gltf-pipeline#114]
I tried to convert a simple OBJ model to glTF, using https://github.com/AnalyticalGraphicsInc/OBJ2GLTF

The resulting fragment shader code contained a line 

    vec3 l = normalize(czm_sunDirectionEC);

but the variable `czm_sunDirectionEC` has not been declared at this point. After a bit of tracing and backward search, it appears that this variable is inserted in the shader by the gltf-pipeline, here:

https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/modelMaterialsCommon.js#L417

(At least this variable name appears nowhere else, and I can't imagine how the shader that is constructed there should be valid when this line is inserted)

**Comment by lilleyse** [comment]
You're right, this line will be a problem for any glTF viewers besides Cesium. In Cesium `czm_sunDirectionEC` is a built-in uniform that is automatically compiled with the shader. Alternatively, the default light could be positioned at the camera's location, similar to COLLADA2GLTF.

**Comment by pjcozzi** [comment]
> Alternatively, the default light could be positioned at the camera's location, similar to COLLADA2GLTF.

We should go with this.  A Cesium-specific pipeline can add `czm_sunDirectionEC` if needed.  This is just a carry-over since this code came from Cesium.
