### ISSUE TITLE
Compress Integer attributes

### ISSUE THREAD

**Issue by lasalvavida** [AnalyticalGraphicsInc/gltf-pipeline#120]
`JOINT` attributes for example are integer values that are currently stored as floats in a lot of models. A `compressIntegerAttributes` stage could be written that checks if an accessor is marked as `float`, but only contains integers, then choosing a suitable int size (and sign) to contain the range.

**Comment by lasalvavida** [comment]
@JoshuaStorm feel free to tackle this one if you have time; otherwise I'll do it eventually

**Comment by pjcozzi** [comment]
Good eye, @lasalvavida!  @JoshuaStorm this is not a priority now.

**Comment by lasalvavida** [comment]
Closed by #121
