### ISSUE TITLE
Attributes that aren't `VEC2`, `VEC3`, or `VEC4` break the pipeline

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#122]
Passing gltf with custom attributes that aren't `VEC2`, `VEC3`, or `VEC4` right now breaks the pipeline. [Example model.](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/343743/hello_AO_vertices_tess.zip) 

Part of the problem is `packArray` in `gltfPrimitiveToCesiumGeometry` but it might also be elsewhere. Since`packArray` uses `readAccessor` it should handle every type that `readAccessor` can process.

**Comment by JoshuaStorm** [comment]
Thanks for the heads up, seems I let this slip by.
