### ISSUE TITLE
How to get MBR from one gltf?

### ISSUE THREAD

**Issue by liyihongcug** [AnalyticalGraphicsInc/gltf-pipeline#138]
How to get MBR from one gltf?

Mbr 's format is below(
"root": {
    "boundingVolume": {
      "region": [
        -1.2960028825819643,
        0.7068325938171807,
        -1.286308749045535,
        0.7141023380151126,
        -11.892070104139751,
        547.7591871983744
      ]
)

**Comment by lilleyse** [comment]
In general the gltf won't contain enough information to give you the bounding rectangle. If you're building a 3D Tileset you'll need to know the longitude, latitude, width, and height of your data in advance.
