### ISSUE TITLE
Images are bigger after encoding with Jimp

### ISSUE THREAD

**Issue by lasalvavida** [AnalyticalGraphicsInc/gltf-pipeline#141]
For example, the CesiumMilkTruck.png from the [glTF sample models](https://github.com/KhronosGroup/glTF/tree/master/sampleModels/CesiumMilkTruck) is 902 KB.

If you run it through Jimp and re-encode it, it ends up as 1,441 KB.

This is obviously not ideal, and it would also be useful to be able to optimize texture images for the web in general.

I did take a brief look at [imagemin](https://www.npmjs.com/package/imagemin) this morning, but I was getting a failure that I think is probably due to AGI's firewall. The [imagemin-optipng](https://www.npmjs.com/package/imagemin-optipng) module has a vendor folder on git with native executables in it that is missing when I get it as an npm module.

Imagemin seems to be the most widely used solution for this, but if we can avoid it, I'd really rather not depend on node modules that have native dependencies.

**Comment by pjcozzi** [comment]
Is this because the resolution changed?  Or because the compression is different?

We should address this soon since this is kinda the opposite of an optimization pipeline.

Longer-term, @lasalvavida is right that we'll want to be able to resize images and more aggressively compress them, especially when the source textures are so big that many texels will map to one pixel at the closest zoom level.

**Comment by lasalvavida** [comment]
> Is this because the resolution changed? Or because the compression is different?

The latter. The resolution is the same.

#142 Compresses without resizing and gets CesiumMilkTruck from 902 KB to 265 KB using lossless png compression.

**Comment by lilleyse** [comment]
> We should address this soon since this is kinda the opposite of an optimization pipeline

@pjcozzi by default the pipeline does not re-encode images, so the pipeline is not making things worse. However these stats show there is definitely room for us to optimize.

**Comment by pjcozzi** [comment]
>>We should address this soon since this is kinda the opposite of an optimization pipeline
>@pjcozzi by default the pipeline does not re-encode images, so the pipeline is not making things worse. However these stats show there is definitely room for us to optimize.

So when is this being used?

**Comment by lilleyse** [comment]
> So when is this being used?

Only when the image is marked as changed, which is only for writing ao into textures.

**Comment by likangning93** [comment]
I'm looking through the [jimp documentation](https://www.npmjs.com/package/jimp#png-and-jpeg-quality), and it looks like there are some controls over png and jpeg quality. I don't know much about the intricacies of png quality, but we can assess how well Jimp's quality controls work and then from there think about reasonable defaults/exposing image quality to users. As with #142, maybe at some point we would even want to make image conversion/compression a feature.

**Comment by likangning93** [comment]
I played around a little with Jimp's `filterType` and `deflateLevel` for PNGs but it looks like the default settings are already pretty much optimal, at least for the milk truck texture.

I took another look at the files, and I suspect a lot of the size difference is from the original texture having a bit depth of 24 while Jimp outputs 36 for RGBA and 24 for RGB without alpha. Jimp's output without alpha is still bigger though, 1.14 MB compared with the 901 KB original.

**Comment by lasalvavida** [comment]
> I played around a little with Jimp's filterType and deflateLevel for PNGs but it looks like the default settings are already pretty much optimal, at least for the milk truck texture.

I did play around with this a little bit as well. They don't seem to compress the image much, if at all.

**Comment by likangning93** [comment]
This might end up being crazy and it would certainly be long-term, but for the sake of future image processing and optimization features, could we consider porting a png quantization algorithm?

**Comment by pjcozzi** [comment]
Just so I'm clear, currently, this is only an issue when writing a texture for AO?  In the future, this will also be an issue when writing texture atlases, so I would address this then.

**Comment by lasalvavida** [comment]
> Just so I'm clear, currently, this is only an issue when writing a texture for AO? In the future, this will also be an issue when writing texture atlases, so I would address this then.

That is accurate. Sounds good to me.

**Comment by pjcozzi** [comment]
Also, lwip is another option for image processing that may fix this (didn't
look at it carefully though).  See
https://www.youtube.com/watch?v=ze7IV-LnzwQ

**Comment by tfili** [comment]
We can also have a look at https://www.npmjs.com/package/pngquant.
