### ISSUE TITLE
gltfPrimitiveToCesiumGeometry doesn't account for compressed attributes

### ISSUE THREAD

**Issue by lasalvavida** [AnalyticalGraphicsInc/gltf-pipeline#149]
Currently, it just reads the values off of the buffer, even though the normals might be oct-encoded, the texture coordinates might be compressed, or any attribute may be quantized.

This creates bad geometry data and as a result, processes like ao that depend on geometry will produce bad results or fail entirely.

If you try to run ao on a quantized box model, the pipeline hangs.

**Comment by ggetz** [comment]
@lilleyse OK to close? Looks like this was addressed with https://github.com/AnalyticalGraphicsInc/cesium-outreach/pull/1140

**Comment by lilleyse** [comment]
I don't think we ever fixed this actually, but now that all compression is Draco based it can be closed. Though we actually need to open a similar issue for Draco. @FrankGalligan has a branch for decoding a Draco model before running it through the pipeline - https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/368#issuecomment-388447383
