### ISSUE TITLE
Exposing helpers

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#153]
As discussed offline, a lot of potentially useful gltf-pipeline helpers aren't being exposed right now. We can keep a running list here. Some ideas for exposing them:
- ~~export a `utils.js` file to gltf-pipeline that exposes useful utils. this to avoid clutter in `index.js`~~
- ~~expose requested utilities as "_private"~~
- ~~just expose everything?~~ Expose a selection

Wishlist:
* [ ] readAccessor
* [ ] getUniqueId
* [ ] packArray
* [ ] byteLengthForComponentType

**Comment by pjcozzi** [comment]
It is perfectly fine to treat the gltf-pipeline public API the same way we treat the Cesium API meaning that these functions could be exposed as individual functions, e.g., like [Cesium.clone](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/clone.js); there's no need to group them into one util class.

**Comment by lasalvavida** [comment]
I will try to get to this today; it's been on my to-do list for a while.

**Comment by lasalvavida** [comment]
Fixed in #157, closing this issue.
