### ISSUE TITLE
combineNodes has problems with oct-encoded or quantized normals

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#176]
`combineNodes` doesn't oct-decode or unquantize the existing normals before apply transforms on them. One solution is to do some checks in `combineNodes` to decode them, transform, then re-encode. Another way could be to store the decoded normals in the extras when the gltf is loaded.

**Comment by lasalvavida** [comment]
This is a more general issue than just `combineNodes`. See #149. All stages that deal with geometry need a way to detect encoding.

**Comment by lilleyse** [comment]
Ah I'm not too surprised. Decoding/re-encoding isn't a great solution either due to the quality loss...
