### ISSUE TITLE
combineNodes conversion issue

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#177]
When running a billboard model through the pipeline I noticed that when `combineNodes` runs the processed model is incorrect. Is it because the root node has a non-identity matrix?

<img width="314" alt="billboard_correct" src="https://cloud.githubusercontent.com/assets/915398/19663863/f52d86b4-9a0b-11e6-8b59-6930bdfc52aa.PNG">
<img width="372" alt="billboard_incorrect" src="https://cloud.githubusercontent.com/assets/915398/19663866/f6c9979c-9a0b-11e6-87f5-2e46863f0c09.PNG">

[treeBillboard.txt](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/549012/treeBillboard.txt)

**Comment by lasalvavida** [comment]
So, this is a tricky one. `combineNodes` flattens out the node transforms onto the points correctly. However, even though this model declares a Y-Up transform in the glTF, the vertex shader discards the rotation and scale of the model matrix and applies the Y-Up transform itself. After conversion, the points are already Y-Up, and then the shader applies the transform again.

If you delete the Y-Up transform node and make `Plane` the root node, this model displays correctly before and after conversion.

I don't think there is a reasonable way to handle people doing custom modifications in the vertex shader like this.

**Comment by lilleyse** [comment]
Ok, thanks for looking into this - and yes it's a weird case.
