### ISSUE TITLE
Review npm dependencies

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/gltf-pipeline#178]
- [x] Since we depend on `bluebird`, there's no reason to also depend on `promise`
- [x] `fs-extra` means we don't need `mkdirp`
- [x] There's no good reason to depend on `underscore`
- [x] `object-values` is literally 11 lines of code and provides no useful benefit
- [x] I'm pretty sure `datauri` usage is unnecessary and can be replaced with one line of code.

There might be more, but this is good low hanging fruit for anyone looking to contribute.

**Comment by lasalvavida** [comment]
`object-values` was removed in #162.

**Comment by pjcozzi** [comment]
Tasklist is complete.

Please reopen if other libraries should be replaced.
