### ISSUE TITLE
Redecleration of `gltf_signNotZero`, `gltf_octDecode` when encoding normals

### ISSUE THREAD

**Issue by bkuster** [AnalyticalGraphicsInc/gltf-pipeline#189]
When encoding normals, but not removing them before hand, the resulting binary gltf cannot be rendered due to `ERROR 0:17 'gltf_signNotZero : function already has a body` (and others in the same fashion, including the `gltf_octDecode` `gltf_oct_dec_a_nromal` `gltf_oct_dec_normal` `gltf_oct_dec_gltf_oct_dec_a_normal` declarations) in Cesium.

Removing the normals before hand or not encoding them works.

The issue has arisen when optimizing a _gltf_ converted with the [COLLADA2GLTF converter v1.0](https://github.com/KhronosGroup/COLLADA2GLTF/) from [this](https://3dwarehouse.sketchup.com/model.html?id=f923282a793a5c71640b2801cae98bff) kmz's collada on an Ubuntu 16.04 machine. The `-b -n -c` flags where set.

**Comment by pjcozzi** [comment]
Thanks for the report, @bkuster!

**Comment by bkuster** [comment]
sure thing, I've been trying to do some debuging myself, so far I've come to the conclusion, that the culprit lies in the `createCombinedVertexShader` of the `Cesium.ShaderSource`. This function adds a ton of newlines and repeats the code block a few times, why I can't figure out yet

**Comment by bkuster** [comment]
I think the issue lies in the generated GLTF. Even though the shaders have a different names, two pairs are exactly the same.

**Comment by pjcozzi** [comment]
@bkuster a PR would be awesome, thanks!  We use the same [Contributor License Agreement (CLA)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) as Cesium so please send in one of those as well.  Let me know if you have any questions.

**Comment by lasalvavida** [comment]
Closed by #192
