### ISSUE TITLE
gltf from blender-exporter

### ISSUE THREAD

**Issue by goetzmoritz** [AnalyticalGraphicsInc/gltf-pipeline#196]
Hi,

I installed gltf-extension and it works with the gltf-files from the gltf-pipeline repo but it does not work with blender-exported gltf-files on my ubuntu 16.04 machine.

using this command:
`node bin/gltf-pipeline.js -i ./input/input.gltf --ao.enable -o output.gltf`

with the attached file
[input.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/660780/input.zip)

brings me this:

> Unhandled rejection Error: EISDIR: illegal operation on a directory

**Comment by lilleyse** [comment]
There's a few issues I noticed:

The `images` section has a `TextureAtlas` texture with an empty uri. It would be best if this image was just removed.

```json
    "images": {
        "TextureAtlas": {
            "uri": ""
        }
    }
```

Some of the material references are empty: `"material": "",`.

Finally there is an issue with khr-materials-common shaders not being encoded correctly, which I submitted a PR for here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/197.

After making these fixes manually I got it to convert:

![model](https://cloud.githubusercontent.com/assets/915398/21317602/d04a809c-c5d3-11e6-885c-923da2dcd14f.jpg)

**Comment by goetzmoritz** [comment]
Thank you, so there are actually a few minor issues. Would be nice if the software would give the user a better feedback about messy models. Is this worth a pull-request?

**Comment by lilleyse** [comment]
The [gltf-validator](http://github.khronos.org/glTF-Validator/) is a useful tool for catching problems ahead of time.

This could deserve a PR though - some of these cases could be caught by the `RemoveUnusedProperties` and other cleanup stages.

**Comment by pjcozzi** [comment]
Generally, please keep validation in the glTF Validator so the effort is not duplicated everywhere.

If the Blender exporter has bugs, please submit them here: https://github.com/Kupoman/blendergltf/issues
