### ISSUE TITLE
Do not overwrite bindShapeMatrix

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/gltf-pipeline#202]
with the identity matrix when adding defaults.

@lasalvavida can you please make this same fix in gltf-pipeline: https://github.com/AnalyticalGraphicsInc/cesium/pull/4792

**Comment by javagl** [comment]
Looking at https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/13b5b65d32d625f3293cf6b1acab357c85eed42b/lib/addDefaults.js#L418 , it seems that this bug did not exist here, as it was fixed (based on some unit test) in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/commit/0fd42083b3fe29c489e8e59bd4111829c948203a

**Comment by pjcozzi** [comment]
Ah yes, shame on me for not also fixing Cesium then.
