### ISSUE TITLE
Add publish instructions to README.md

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/gltf-pipeline#206]
and give me access to publish, please :)

I suppose it is:
* Update the version in `package.json` to match the latest version in CHANGES.md, then run
```
npm run prepublish
npm publish
```

**Comment by lilleyse** [comment]
I added you to the access list: https://www.npmjs.com/package/gltf-pipeline/access

**Comment by pjcozzi** [comment]
Thanks.

Deployed @mlimper's updates.

Added instructions in #208.
