### ISSUE TITLE
After optimizations, meshes with greater than 65535 vertices still written to ushort buffer.

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/gltf-pipeline#230]
This causes an exception in node. I'm seeing the issue in `combinePrimitives`.

**Comment by pjcozzi** [comment]
With glTF 2.0, we can use uint32.

**Comment by likangning93** [comment]
@pjcozzi do you think it's worthwhile in the meantime to have `combinePrimitives` check if combining will exceed uint16?

**Comment by pjcozzi** [comment]
Yes, let's check for glTF 1.0.

CC @lasalvavida

**Comment by likangning93** [comment]
I'm checking this out now, in case anyone else was working on it.
