### ISSUE TITLE
Unexpected output location

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-pipeline#244]
When I run the pipeline with output like this:

`node gltf-pipeline.js ... -o /d/my_folder/my_file.gltf`

I get an unexpected result, a new `output` folder is created and the actual path written is:

`/d/my_folder/output/my_file.gltf`

This is mentioned in a [comment buried in a large cleanup issue](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/130#issuecomment-232756157), but I feel this warrants its own dedicated issue.  It seems quite unnatural for it to create a subfolder when I specifically targeted a folder and filename.  It's bad for scripting too.

**Comment by shehzan10** [comment]
Actually there are couple of different things happening based on the options which I will try to summarize here:

Input Options | Output File
----------------|--------------
`-i /path/to/input.gltf -o /path/to/result.gltf` | /path/to/**output/** result.gltf
`/path/to/input.gltf  /path/to/result.gltf` | /path/to/**output/** result.gltf
`-i /path/to/input.gltf` | /path/to/**output**/input **-optimized**.gltf
`/path/to/input.gltf` | /path/to/**output**/input **-optimized**.gltf

I think the best option would be to remove the directory creation (which seems to happen in all cases) and go with the suffixed -optimized if output is not specified.

@lilleyse thoughts?

**Comment by lilleyse** [comment]
Yes definitely agree. Creating the output directory has gone back to the way beginnings of this project, but I would be fine with changing it.

**Comment by pjcozzi** [comment]
@shehzan10 can you make this change?

**Comment by pjcozzi** [comment]
Ah, I see #245, thanks!
