### ISSUE TITLE
No technique in output

### ISSUE THREAD

**Issue by alculquicondor** [AnalyticalGraphicsInc/gltf-pipeline#273]
I'm trying to use glTF to deliver geometry data only (I have my own shaders and textures). Is it possible to add a flag parameter such that an asset is output with no technique nor shaders? I'm trying to optimize file size. Binary glTF is a must in my case.

**Comment by lilleyse** [comment]
You can use `--kmc.enable` to export with materials only. (This is flag is also in `obj2gltf` as `--kmc`).
