### ISSUE TITLE
RemoveUnusedProperties in removePrimitiveAttributes tries to remove undefined technique

### ISSUE THREAD

**Issue by bkuster** [AnalyticalGraphicsInc/gltf-pipeline#280]
After removing the normals in the Pipeline with `removeNormals` a material is left without a `technique`. The technique referenced _before_ the normals where removed is also no longer available. In the `removeAll` step of the pipeline following the `removeNormals`, the removePrimitiveAttributes tries to access the material and its technique at *line 400* of `RemoveUnusedProperties.js` . The material exists, but the technique returns undefined, causing an unhandled rejection.

Im not sure if a) the material should have been removed at the same time as the technique its using was removed in `removeNormals` or b) the `removePrimitiveAttributes` function should be able to handle a missing technique.

**Comment by bkuster** [comment]
If I try to _ignore_ the missing technique in the material, the issue reemerges in `processModelMaterialCommons.ensureSemanticExistenceForPrimitive` at line 806, when the program should be accessed. This leads me to believe the issue actually lies in the `removeNormals` step?

**Comment by lilleyse** [comment]
`removeNormals` should regenerate the technique, but I guess it doesn't update the material properly. I'll look into this in a bit. Thanks for the detailed report!
