### ISSUE TITLE
Load and decode images on demand

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#281]
`gltf-pipeline` currently loads all of a gltf's images using Jimp up-front in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/loadGltfUris.js. For texture-heavy models this is a pretty major performance problem, since decoding is slow and also eats an enormous amount of memory. A lot of optimizations in the pipeline also don't do anything with those textures, so we could potentially speed up optimization for a lot of models just by loading images as needed.

**Comment by lilleyse** [comment]
No longer a problem in `master`, which doesn't even include Jimp anymore.
