### ISSUE TITLE
simplification for gltf

### ISSUE THREAD

**Issue by lty1024** [AnalyticalGraphicsInc/gltf-pipeline#290]
I am a new man in glTF. I'm trying to stream a big size glTF model. While the higher detail is not needed, so I compressed the texture images. But the size is still not small enough, so I wonder if there is any way to simplify the model by compressing the triangles, including the textured models.
Thank you for your help!

**Comment by lilleyse** [comment]
You can use the `--quantize`, `--encodeNormals`, and `--compressTextureCoordinates` flags to compress positions, normals, and texture coordinates respectively. Also resizing the input textures may help too if you have a lot of texture data.

**Comment by lty1024** [comment]
I tried the flags and no error reported. The size of model is down about 30%. But after I converted it to .b3dm model, it cannot be visualized in my browser. And the gltf model cannot be visualized too. The decompressed model can be visualized. Please give me some advise. 
Thanks for your patience!

**Comment by lilleyse** [comment]
Hm.. can you send over the model you're converting? That will help us debug the problem. Feel free to upload it here or send it to me at slilley@agi.com.
