### ISSUE TITLE
Detect identical chains of material/technique/program/shader

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#292]
`gltf-pipeline` currently doesn't detect identical chains of materials, techniques, programs, and shaders, so when combining primitives it won't combine primitives that have identical materials/techniques/programs/shaders that are just labelled differently.

This is a problem for projects that programmatically generate glTF and rely on `gltf-pipeline` for optimization, which is one of the big intended use cases.

**Comment by likangning93** [comment]
We're aware that `gltf-pipeline` kind of does this already, there's something that compares shaders and merges them. But it doesn't seem to be robust enough... I'll try to come up with a good test case to demonstrate.

**Comment by lilleyse** [comment]
@likangning93 could you check if this is fixed for you now? -- https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/305

**Comment by likangning93** [comment]
Seems to work like a charm! Thanks!

**Comment by lilleyse** [comment]
Awesome! Thanks @shehzan10.
