### ISSUE TITLE
generating face normals may leave some extra data around

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/gltf-pipeline#299]
It looks like the original position data may not be cleared.

Also the test `generates face normals if they do not exist` doesn't actually test anything, because smooth normals are generated in a previous test. We need to set these tests up to use fresh copies of the models.

**Comment by likangning93** [comment]
> Also the test `generates face normals if they do not exist doesn't actually test anything

Woah, looks like there's errors in this code path that must have slipped by because of this: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/generateNormals.js#L99
