### ISSUE TITLE
.glb crash on load with duplicate images

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/gltf-pipeline#302]
If a .glb file has an image in a binaryGltf bufferview and it is referenced by 2 separate `images` the file will fail to load.

It's because `parseBinaryGltf` calls `loadSourceFromBody` which loads each image into a `Buffer` and removes the binaryGltf bufferview. So it works as intended for the first image, but the second image crashes as the bufferview is no longer there.

To handle this correctly we probably need to detect duplicate binaryGltf images and shaders on load, because we also need to be sure that the fix doesn't duplicate the same image in the output .glb file.

**Comment by lilleyse** [comment]
The crash has been fixed. I opened an issue specifically for not duplicating the same image in the output. https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/416
