### ISSUE TITLE
Support for occlusion in shader generation

### ISSUE THREAD

**Issue by javagl** [AnalyticalGraphicsInc/gltf-pipeline#315]
While browsing over the code at https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/processModelMaterialsCommon.js I noticed that there does not seem to be support for [`material.occlusionTexture`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialocclusiontexture) . Is this supposed to be added later, or did I overlook it?

<sub>I'm not actively *using* the pipeline right now, so this is low prio, one way or the other. I'm asking this merely out of curiosity...</sub>

**Comment by lilleyse** [comment]
The `processModelMaterialsCommon` and `processPbrMetallicRoughness` functions have been moved out of `gltf-pipeline`, but the Cesium PBR implementation handles the occlusion texture.
