### ISSUE TITLE
generating face normals can cause uint16 overflow

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#317]
Running with the remove and generate face normals flags (`-r -f`) can cause `uint16` overflow, since `gltf-pipeline` clones vertices so they are only ever used once.

Something to be aware of when using `gltf-pipeline` to compute normals or correct winding order, which uses compute normals.

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/409 (on the 1.0 branch).
