### ISSUE TITLE
Status of 2.0 branch?

### ISSUE THREAD

**Issue by donmccurdy** [AnalyticalGraphicsInc/gltf-pipeline#329]
Hi, there's an undocumented 2.0 branch — just wondering what the status of that is? At this point I think I'd prefer to advise people to use an beta branch than to use glTF1 assets, and there are a lot of people looking for a way to convert glTF1 to glTF2.

**Comment by lilleyse** [comment]
The 2.0 branch here is very Cesium-centric right now and probably not best to recommend for general use yet. The models produced here use the [KHR_technique_webgl](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_technique_webgl) extension.

There has been some work on a different branch called `cleanup` which aims to be the next version of `gltf-pipeline` but this is too early to recommend as well.

One of the toughest questions right now is how to convert the materials from glTF 1.0 style to PBR. Even figuring out which uniforms represent the diffuse and specular components requires some guesswork. As far as I can tell, `KHR_technique_webgl` isn't widely supported.

**Comment by donmccurdy** [comment]
Thanks for clarifying! The KHR_technique_webgl extension was never finalized (indeed, the spec says "DO NOT IMPLEMENT" 😁  ) so we do not support it in three.js or A-Frame.

FWIW, the glTF Blender exporter does convert lambert/phong materials to PBR in a way that seems "good enough". If there were a task list of issues that must be solved to make glTF 2.0 ready for public alpha/beta testing, I think we could probably rally some support around that. Perhaps this issue, or a new milestone tracking all related issues? Hopefully finalization and adoption of the `KHR_technique_webgl` extension is not a blocker here.

**Comment by lilleyse** [comment]
Yes a more concrete task list would help a lot and I'll get one together soon. Having the community help move this project along would be great! Minus the material translation, we already support a good deal of the 1.0-2.0 conversion so I'm hoping this is closer than it seems.

For the material conversion I'm more referring to how glTF 1.0 material property names are generic, and you don't know that something called "diffuse" is actually the diffuse color. The generic technique/shader approach doesn't seem to map easily to glTF 2.0 concepts, but it should still be doable.

I'm definitely on board with `KHR_technique_webgl` not being a blocker here, I'd like to make that completely optional.

**Comment by lilleyse** [comment]
@donmccurdy I opened a 2.0 roadmap here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/330

**Comment by donmccurdy** [comment]
Thanks! Closing this issue and following #330.
