### ISSUE TITLE
Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by hblanken** [AnalyticalGraphicsInc/gltf-pipeline#334]
I installed on Linux. The same happens on MacOS.
running node 8.8.1

I run this command and get error.
node ./bin/gltf-pipeline.js -i test.gltf -o test1.gltf

Unhandled rejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.isAbsolute (path.js:1200:5)
    at loadURI (/home/ec2-user/gltf-pipeline/lib/loadGltfUris.js:98:31)
    at loadGltfUris (/home/ec2-user/gltf-pipeline/lib/loadGltfUris.js:34:9)
    at /home/ec2-user/gltf-pipeline/lib/readGltf.js:51:20
    at tryCatcher (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ec2-user/gltf-pipeline/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by lilleyse** [comment]
Hi @hblanken

Could you send over the model that you're testing with?

**Comment by mordka** [comment]
I think it's missing material image URIs. It fails on the line https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/4048384cc296a959bf873a6b791c7a8a79442f7f/lib/loadGltfUris.js#L34
The gltf.images is equal to:
```[   mimeType: 'image/png',
    bufferView: 3,
    extras: { _pipeline: {} } },
    { name: 'material0001_map_Kd',
      mimeType: 'image/png',
      bufferView: 4,
      extras: { _pipeline: {} } },
    { name: 'material0002_map_Kd',
      mimeType: 'image/png',
      bufferView: 5,
      extras: { _pipeline: {} } },
    { name: 'material0003_map_Kd',
      mimeType: 'image/png',
      bufferView: 6,
      extras: { _pipeline: {} } },
    { name: 'material0004_map_Kd',
      mimeType: 'image/png',
      bufferView: 7,
      extras: { _pipeline: {} } },
    { name: 'material0005_map_Kd',
      mimeType: 'image/png',
      bufferView: 8,
      extras: { _pipeline: {} } },
    { name: 'material0006_map_Kd',
      mimeType: 'image/png',
      bufferView: 9,
      extras: { _pipeline: {} } },
    { name: 'material0007_map_Kd',
      mimeType: 'image/png',
      bufferView: 10,
      extras: { _pipeline: {} } },
....]```

**Comment by hblanken** [comment]
hi @lilleyse - As @mordka says - we are testing to convert obj and Wavefront mtl files from here: https://github.com/OpenDroneMap/OpenDroneMap/blob/58ff03a6cea824f245bf5debc54f007d0bb2522a/modules/odm_texturing/src/OdmTexturing.cpp

The gltf generated with obj2gltf is 182MB large and seems to be missing image URIs. Is the above info enough or shall I send you the entire file?

**Comment by lilleyse** [comment]
The problem here might be that obj2gltf outputs glTF 2.0 models but gltf-pipeline is still stuck at glTF 1.0. In 2.0 images can be stored in a bufferView rather than a dataUri, so `obj2gltf` uses this approach.

If you need to use `gltf-pipeline`, you could try using the [`1.0` branch](https://github.com/AnalyticalGraphicsInc/obj2gltf/tree/1.0) of `obj2gltf`.

**Comment by hblanken** [comment]
Hi Sean - thanks for the quick suggestion. Indeed running the original gltf through the validator it shows version 2.0.
Switchign to branch 1.0 does not help unfortunately. 
The gITF-validator gives us this for the gltf created by branch 1.0
'[
    {
        "uri": "test.gltf",
        "mimeType": "model/gltf+json",
        "errors": {
            "EMPTY_ENTITY": [
                {
                    "type": "EMPTY_ENTITY",
                    "path": "#/extensionsUsed",
                    "message": "Entity can not be empty."
                }
            ],
            "UNKNOWN_ASSET_MAJOR_VERSION": [
                {
                    "type": "UNKNOWN_ASSET_MAJOR_VERSION",
                    "path": "#/asset",
                    "message": "Unknown glTF major asset version: `1`."
                }
            ]
        },
        "warnings": {
            "UNEXPECTED_PROPERTY": [
                {
                    "type": "UNEXPECTED_PROPERTY",
                    "path": "#/programs",
                    "message": "Unexpected property."
                },
                {
                    "type": "UNEXPECTED_PROPERTY",
                    "path": "#/shaders",
                    "message": "Unexpected property."
                },
                {
                    "type": "UNEXPECTED_PROPERTY",
                    "path": "#/techniques",
                    "message": "Unexpected property."
                },
                {
                    "type": "UNEXPECTED_PROPERTY",
                    "path": "#/asset/profile",
                    "message": "Unexpected property."
                },
                {
                    "type": "UNEXPECTED_PROPERTY",
                    "path": "#/asset/premultipliedAlpha",
                    "message": "Unexpected property."
                }
            ]
        },
        "info": null
    }

**Comment by lilleyse** [comment]
gltfviewer and gltf-Validator may not have gltf 1.0 support either. I'm not sure why gltfviewer doesn't show the textures for the 2.0 model though, I would have to look at the file to see.

Out of curiosity is there a specific function you are using gltf-pipeline for? It may be possible to achieve it some other way, at least until the 2.0 branch is ready.

**Comment by hblanken** [comment]
We are using gltf-pipeline to recreate normals. We suspected that our obj and mtl might not be correctly encoded, as gltfviewer only shows the object and no texture. If you suggest a good place to post the obj, mtl and textures png you could find out for yourself. (they are 200MB-300MB total)

**Comment by lilleyse** [comment]
Alright, maybe it is having trouble rendering it without normals. One way to generate normals is to import and export the model from Blender, but that's not that best programmatic solution. Keep an eye on the `2.0` branch in the meantime.
