### ISSUE TITLE
Output from compressing embedded glTF 2.0 contains no content

### ISSUE THREAD

**Issue by xeolabs** [AnalyticalGraphicsInc/gltf-pipeline#341]
Running gltf-pipeline 1.0.2 on Ubuntu 16:04, to compress embedded glTF 2.0, I'm ending up with a glTF file with no meshes or buffers in it. Maybe there are options I'm missing?

Input file (a test model from Khronos): https://github.com/xeolabs/xeogl2/blob/master/examples/models/gltf/2CylinderEngine/glTF-Embedded/2CylinderEngine.gltf

My output: https://gist.github.com/xeolabs/99125213dc907f1a2e5e96c0a0ba9859

My usage:
````
node ./bin/gltf-pipeline.js -i models/gltf/2CylinderEngine/glTF-Embedded/2CylinderEngine.gltf -o models/gltf/2CylinderEngine/glTF-Embedded/2CylinderEngine-optimized.gltf --stats

Statistics for models/gltf/2CylinderEngine/glTF-Embedded/2CylinderEngine.gltf
------------------
Total size of all buffers: 1794612 bytes
Images: 0
Draw calls: 34
Rendered primitives (e.g., triangles): 75730
Nodes: 82
Meshes: 29
Materials: 34
Animations: 0
External requests (not data uris): 0

Statistics for models/gltf/2CylinderEngine/glTF-Embedded/2CylinderEngine-optimized.gltf
------------------
Total size of all buffers: 0 bytes
Images: 0
Draw calls: 0
Rendered primitives (e.g., triangles): 0
Nodes: 1
Meshes: 0
Materials: 0
Animations: 0
External requests (not data uris): 0
````

**Comment by lilleyse** [comment]
Unfortunately `gltf-pipeline` doesn't support glTF 2.0 models yet. Keep an eye on the roadmap - https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/330. We hope to get this into shape in January (time permitting).
