### ISSUE TITLE
Remove empty animations

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/gltf-pipeline#344]
@lilleyse does gltf-pipeline already do this?

e.g.
``` json
        "animation_1": {
            "channels": [],
            "count": 16,
            "parameters": {
                "TIME": "animAccessor_0"
            },
            "samplers": {}
        },
```

Replaces https://github.com/KhronosGroup/glTF/issues/333

**Comment by lilleyse** [comment]
No it doesn't.

That actually goes against the spec, where `minItems` of channels and samplers is 1.
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.schema.json

**Comment by lilleyse** [comment]
Though this used to be allowed in the 1.0 spec and just wasn't handled here.

**Comment by pjcozzi** [comment]
Ah, I would say OK to close this then, thanks!
