### ISSUE TITLE
Support for KHR_draco_mesh_compression.

### ISSUE THREAD

**Issue by donmccurdy** [AnalyticalGraphicsInc/gltf-pipeline#348]
glTF-Pipeline should include an opt-in flag to apply Draco mesh compression to an existing glTF asset. Opening this bug to track.

Branch in progress, by @FrankGalligan and the Draco team, here: https://github.com/FrankGalligan/gltf-pipeline/tree/draco_compression_extension

**Comment by pjcozzi** [comment]
OK to close given #353?

**Comment by lilleyse** [comment]
Yes
