### ISSUE TITLE
I always get a basically empty gltf file when using this

### ISSUE THREAD

**Issue by soadzoor** [AnalyticalGraphicsInc/gltf-pipeline#364]
Hi,

I'm very happy to see some progress on this project, I just saw that draco compression is now merged into the 2.0 branch, which is very nice. So I immediately tried it, but I always get an empty gltf file.

Later it turned out, I get the same empty file when I'm not using the draco flag as well. I tried with different models, and settings (glb, gltf+bin, everything embedded in gltf, etc..), none of them seem to work with this.

My input and output file: 
[gltf.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/1953350/gltf.zip)

A screenshot with the details:
![capture](https://user-images.githubusercontent.com/10392261/39337140-a65711e8-49bb-11e8-8ec5-473ebf0d3327.PNG)

What am I missing?

**Comment by soadzoor** [comment]
Also, there's a typo in the README.md of the 2.0 branch:
`gltf-pipeline.js -i model.gltf -d -s -o modelDraco.gltf`

The `gltf-pipeline.js` should be `gltf-pipeline`, without the `.js` part, I guess.

**Comment by lilleyse** [comment]
Are you definitely on the 2.0 branch? I ran the same command as you (excluding `--stats` which crashed - fixing now), and it produced the correct output.

**Comment by soadzoor** [comment]
Oh, geez, yea you're right. I was on the 2.0 branch, but following the README without thinking wasn't really a good idea afterall, because
`npm install -g gltf-pipeline` installs the 1.03 version, or so.

So now it works with `npm install` instead `npm install -g gltf-pipeline` and `node bin/gltf-pipeline.js` instead `gltf-pipeline`.

Thank you for the idea!

Maybe you could update the `README` with this, that would help some noobies, like me ;)
Thanks again,

Cheers!

**Comment by soadzoor** [comment]
Thanks! :)
