### ISSUE TITLE
After Draco compression, glTF-viewer reports errors with accessors missing normalized

### ISSUE THREAD

**Issue by my2iu** [AnalyticalGraphicsInc/gltf-pipeline#368]
I made a glTF file with color accessors of the form: 
  {"bufferView":0,"byteOffset":12,"componentType":5121,"count":1790,"type":"VEC4","normalized":true}

After compressing them with 
  node bin\gltf-pipeline.js -i ..\chibi-dog-125.idx.glb -d

The file ended up with color accessors listed as
  {"componentType":5121,"count":1790,"type":"VEC4"}

When viewing the file in the donmccurdy online gltf viewer, there are complaints about the lack of "normalized" in the accessors, and the file is rendered without proper normalization of color values.

> Invalid accessor format '{VEC4, UNSIGNED_BYTE}' for this attribute semantic. Must be one of ('{VEC3, FLOAT}', '{VEC3, UNSIGNED_BYTE normalized}', '{VEC3, UNSIGNED_SHORT normalized}', ..., '{VEC4, UNSIGNED_BYTE normalized}', '{VEC4, UNSIGNED_SHORT normalized}').

I'm not sure if this is an error with the compressed file or the gltf viewer.

--

Also, is there a command for uncompressing draco files using this tool?

**Comment by lilleyse** [comment]
Thanks for the bug report, I believe this is fixed now (https://github.com/AnalyticalGraphicsInc/gltf-pipeline/commit/5bcd878adb9a118f239abe24e5b95acef3548146). The `normalized` property was not getting transferred properly and the data was being written as floats instead of unsigned byte.

> the file is rendered without proper normalization of color values

I opened a bug report for that here: https://github.com/donmccurdy/three-gltf-viewer/issues/91
Cesium has a similar issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/6561
> Also, is there a command for uncompressing draco files using this tool?

I believe @FrankGalligan was planning on opening a PR for doing that.

**Comment by FrankGalligan** [comment]
Yes I have a WIP here: https://github.com/FrankGalligan/gltf-pipeline/tree/decompress_draco

**Comment by my2iu** [comment]
I haven't had time to dig into the Draco file formats and reverse engineer what it does, but is Draco actually able to recreate the structure of buffers from before compression? I don't see enough information left in the glTF JSON after compression to do so, but maybe that information is recorded in the Draco-encoded data?

For example, if I stuff the data from multiple meshes into a single buffer and I have a specific memory/buffer layout for everything (e.g. position as float32, UV as int16, color as int8). After compression and then decompression, will I get back a single buffer with the same memory layout (obviously, the data itself will be lossy)? Will the layout of triangle primitives within a buffer also be the same? Or will I get a bunch of separate buffer views, separated by mesh, that I will have to stitch back together into the memory layout that I want?

**Comment by lilleyse** [comment]
Draco will not break up primitives but the data itself may be shuffled around. The order of triangles and attribute data will not be the same as the source data, and as far as I know the operation can't be reversed.

There is a way to enable sequential encoding in the encoder which preserves the ordering. The compression might be worse, but is this an option you would like to see exposed by gltf-pipeline?

**Comment by my2iu** [comment]
I think it's better if I just wait until there's better documentation on how Draco is encoded in gltf files, and then I'll just create my own pipeline tools.
