### ISSUE TITLE
Error when compressing glTF model with DRACO compression

### ISSUE THREAD

**Issue by FarhadG** [AnalyticalGraphicsInc/gltf-pipeline#369]
I've been researching on how to compress a multi-texture OBJ with DRACO to be able to render in THREE.js. Anyways, after some discussions in [this](https://discourse.threejs.org/t/mapping-multiple-materials-to-an-obj-model-in-three-js/2577) thread, I was advised to convert the OBJ to glTF and then leverage the V2 branch here to compress the glTF with DRACO compression.

Here are my steps:
1) Generated a 3D OBJ model with OpenDroneMap. You can download a model with [WebODM](https://demo.webodm.org/3d/project/3/task/904c1c56-10c5-48df-a104-0138f699dd69/)
2) Converted the multi-texture OBJ to glTF via https://github.com/AnalyticalGraphicsInc/obj2gltf
3) Tried to compress the new glTF via v2 branch and got the following error:

```
$ node ./gltf-pipeline/bin/gltf-pipeline.js -i odm/odm_textured_model.gltf  -d --stats

Statistics before:
Total byte length of all buffers: 60397176 bytes
Images: 4
Draw calls: 4
Rendered primitives (e.g., triangles): 193353
Nodes: 1
Meshes: 1
Materials: 4
Animations: 0
External requests (not data uris): 0
1
1
abort(1). Build with -s ASSERTIONS=1 for more info.
```

Thank you for your help and assistance.

**Comment by lilleyse** [comment]
Thanks @FarhadG 

It seems like this is an error from within the draco library. @FrankGalligan would you be to take a look at this? I uploaded the gltf here: https://drive.google.com/open?id=1u8oSGfsDpPTxD41MuJusbPahI126t9qC.

If it helps with debugging, primitive at index 3 is failing at `EncodeMeshToDracoBuffer`. Also the model converts correctly if `MESH_SEQUENTIAL_ENCODING` is applied.

This also reveals a secondary issue where mesh data is encoded multiple times when primitives share the same attributes but have different indices. I might have a chance later to look into that. For example the original glTF looks like:

```
        {
          "attributes": {
            "POSITION": 0,
            "NORMAL": 1,
            "TEXCOORD_0": 2
          },
          "indices": 5,
          "material": 2,
          "mode": 4
        },
        {
          "attributes": {
            "POSITION": 0,
            "NORMAL": 1,
            "TEXCOORD_0": 2
          },
          "indices": 6,
          "material": 3,
          "mode": 4
        },
```

**Comment by lilleyse** [comment]
Fixed the secondary issue in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/commit/734f85d26e766834347cb2ec835a6c694b970734 by adding a stage that splits primitives that share the same attributes but have different indices. This unintentionally fixed the draco crash too. The model now converts correctly.

**Comment by FarhadG** [comment]
Thank you, @lilleyse! It works like a charm. Do we have an idea of when `v2` will be stable and merged into master?

**Comment by lilleyse** [comment]
The last two things it needs are tests for `compressDracoMeshes` and a couple other files, and support for [KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/pull/1296) so that we can upgrade from 1.0 to 2.0 properly.

There's been a lot of momentum lately so I'm hopeful it will be soon!

**Comment by FarhadG** [comment]
That's awesome, @lilleyse. Another question: I understand that Draco offers other functionality in their compression than what I see outlined in the `V2` branch. Will those be available soon? For example, the `metadata` and being able to omit certain data.

**Comment by lilleyse** [comment]
It's unclear to me how the metadata fits into the glTF extension, and how it should be accessed by engines. In glTF metadata usually goes in the `extras` properties. Maybe the Draco metadata is designed for standalone draco files not already contained in a glTF?

To keep it simple I think the draco encoding should be all or nothing, since it might get complicated to describe which primitives/attributes should be omitted. Though if you want to avoid compressing a certain type of attribute you can set its quantization bits to 0 - for example `--draco.quantizePosition=0`.

**Comment by DimitarMitrov** [comment]
@FarhadG You noted that you use "multi-texture OBJ". Does it mean that you use - multiple meshes with different materials/textures? Because that is what I am trying to achieve, without success so far, and in obj2gltf documentation is stated that multiple materials are not supported.
