### ISSUE TITLE
[Branch 2.0-cesium] index.js requires some missing files

### ISSUE THREAD

**Issue by silvainSayduck** [AnalyticalGraphicsInc/gltf-pipeline#375]
In `index.js`:

```js
module.exports = {
  // ...
  combineMeshes : require('./lib/combineMeshes'),
  // ...
  getUniqueId : require('./lib/getUniqueId'),
  // ...
};  
```
Both of those files are not present in the `lib` folder of branch `2.0-cesium`. 

Am I missing something in the way this should be used?

**Comment by lilleyse** [comment]
We don't recommend using the `2.0-cesium` branch directly.

Instead check out the main [2.0 branch](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0) which is more stable.

**Comment by silvainSayduck** [comment]
Thanks! Indeed, after looking a bit deeper, I realized there seems to be a lot of glTF 1.0 left in 2.0-cesium.

However, the 2.0 branch does not provide the ambient occlusion generation possibility yet, if I'm correct?

**Comment by lilleyse** [comment]
That's correct - we're trying to trim down gltf-pipeline and ambient occlusion will be removed. You can still use `master` to generate ambient occlusion for glTF 1.0 models and then convert them to 2.0, however we still don't have a perfect way to transform glTF 1.0 materials/techniques/shaders to glTF 2.0 materials, except to use the upcoming [KHR_techniques_webgl extension](https://github.com/KhronosGroup/glTF/pull/1296).

**Comment by silvainSayduck** [comment]
Alright, thanks for the clarification!
