### ISSUE TITLE
Can't seem to compress gltf files using the gltf-pipeline tool

### ISSUE THREAD

**Issue by purelight01** [AnalyticalGraphicsInc/gltf-pipeline#377]
Hello,
I have tried to compress my sample gltf files using the gltf-pipeline tool. I tried various flags but usually got the empty results like shown below.
Could someone please tell me what's the right flags to use for compression purpose ?

Here is what I typed:

gltf-pipeline -c -i scene.gltf -o output.gltf --stats

Results:
---
Statistics for scene.gltf
------------------
Total size of all buffers: 4724320 bytes
Images: 35
Draw calls: 38
Rendered primitives (e.g., triangles): 70008
Nodes: 42
Meshes: 38
Materials: 35
Animations: 0
External requests (not data uris): 36

Statistics for scene-optimized.gltf
------------------
Total size of all buffers: 0 bytes
Images: 0
Draw calls: 0
Rendered primitives (e.g., triangles): 0
Nodes: 1
Meshes: 0
Materials: 0
Animations: 0
External requests (not data uris): 0

optimize: 2652.645ms

There is a only a single gltf file under the output dir. It contains pretty much 0 attributes - this is not correct.

**Comment by lilleyse** [comment]
It seems like you might be running a glTF 2.0 model through either the npm package or the master branch here, which is still using glTF 1.0.

Make sure to checkout the [2.0 branch](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/2.0/README.md) and then run:

`node bin/gltf-pipeline.js -i model.gltf -d --stats`

This will apply [Draco](https://github.com/google/draco) compression to your model.
