### ISSUE TITLE
Newbie question on gltf-pipeline

### ISSUE THREAD

**Issue by hololite** [AnalyticalGraphicsInc/gltf-pipeline#378]
Trying to use the gltf-pipeline for the first time.
I have a sample gltf model attached below.
The tool has lots of options, I am not too sure which one to use, for my purpose I just want to have the geometry info compressed so I am kinda guessing here. 
Here is my command I used.

**gltf-pipeline -i cornellBox\cornellBox-PBR.gltf  -o output.gltf**

The output dir contains the following:

06/18/2018  07:44 PM               513 output.gltf
The contents are:
**{"accessors":{},"asset":{"generator":"Khronos Blender glTF 2.0 exporter","version":"2.0","premultipliedAlpha":false,"profile":{"api":"WebGL","version":"1.0.3"}},"bufferViews":{},"buffers":{},"images":{},"materials":{},"meshes":{},"nodes":{"rootNode":{"children":[],"meshes":[],"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}},"samplers":{},"scene":0,"scenes":[{"name":"Scene","nodes":["rootNode"]}],"textures":{},"animations":{},"cameras":{},"programs":{},"shaders":{},"skins":{},"techniques":{},"extensionsUsed":[]**

Which does not look correct to me.
What did I miss ? Can I run the tool on any gltf models in general, or do I need to normalize the gltf data first etc ?

[cornellBox.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/2113646/cornellBox.zip)

**Comment by hololite** [comment]
Note the version of this tool I use:

C:\Temp>gltf-pipeline --version
1.0.4

This is the npm package version which has the cmd script wrapper.
I also tried the github js version. They both gave the same results.

**Comment by lilleyse** [comment]
The npm package and master branch on github are still based on glTF 1.0.

Make sure to checkout the [2.0 branch](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/2.0/README.md) and then run:

`node bin/gltf-pipeline.js -i model.gltf -d --stats`

This will apply [Draco](https://github.com/google/draco) compression to your model.

**Comment by hololite** [comment]
Thanks for the help! Yes it works now!

Do you have any plans to support --optimizeDrawCalls in the 2.0 ver of the tool ?

**Comment by lilleyse** [comment]
Nice!

Initially we are keeping the 2.0 version lean, so that will not be included to start.
