### ISSUE TITLE
Draco compression causes gap/holes in meshes

### ISSUE THREAD

**Issue by hololite** [AnalyticalGraphicsInc/gltf-pipeline#379]
After applying the -d (for draco compression) option on my sample model, I noticed that all meshes show small gaps on every edges. The sides (of rectangular shapes) are not fully connected. So this looks like the actual geometries have been altered by the compression algo ?

I tried applying --draco.compressionLevel <number>, with several different levels including 1. This does not help, the gaps are still there.

Is this altered result expected ? Can I use one of the --draco.quantizeXxx options to fix this issue ?

thank you.

**Comment by lilleyse** [comment]
Do you have before and after screenshots? The compression does alter the geometry so some changes are expected.

Increasing `draco.quantizePositionBits` may help, but also check out `draco.unifiedQuantization`:

> Quantize positions of all primitives using the same quantization grid defined by the unified bounding box of all primitives. If this option is not set, quantization is applied on each primitive separately which can result in gaps appearing between different primitives.

**Comment by hololite** [comment]
Yes the draco.unifiedQuantization alone actually fixed the issue. You are genius! :)
(... and I should've read the help messages carefully too).
The compression size increases only a bit, almost negligible.
I wonder why this is not turned on by default ? 

Btw I tried the draco.quantizePositionBits and other draco.quantizeXxx options, did not help though.

**Comment by lilleyse** [comment]
Cool I'm glad that option worked. There are some cases where unified quantization can make things worse, like if a glTF is composed of multiple primitives that are far apart from each other. But maybe it would make sense to turn it on by default if people commonly get artifacts like yours.
