### ISSUE TITLE
Decoding time is too long

### ISSUE THREAD

**Issue by jkfhto** [AnalyticalGraphicsInc/gltf-pipeline#381]
Rendering a 150M gltf model locally using three.js requires about 4-5 display pages, but with the gltf-pipeline compressed model, the display takes about 8 seconds. Why is that?

**Comment by lilleyse** [comment]
The extra loading time is for decoding the compressed data. This is just the standard tradeoff when using compression, the model is smaller and faster to download but must be decoded before it can be rendered.

**Comment by jkfhto** [comment]
Is the difference between the two rendering times above correct? If it is normal, then under what circumstances is it appropriate to use gltf-pipeline to encode data for rendering?@lilleyse

**Comment by jkfhto** [comment]
How do I send the model to you? @lilleyse

**Comment by lilleyse** [comment]
You can send me a download link - slilley@agi.com

**Comment by jkfhto** [comment]
This is a download link：
[https://sketchfab.com/models/25e0167e6d074d8e9896786b1ae67582 ](url)
@lilleyse

**Comment by lilleyse** [comment]
I see a reduction from 174 MB to 34.6 MB (152 MB to 13 MB ignoring textures). That's really good.

Both ThreeJS and Cesium load it in 3-4 seconds on my machine. I think everything is working as expected, you'll just have to decide if the decode time is a problem. If it is, you can also just gzip the model, which produces a larger compressed file (45 MB), but can be decoded extremely quickly by the browser. `gltf-pipeline` hasn't have a command to gzip but there are other tools out there.

**Comment by jkfhto** [comment]
Will the time you use three.js be the model load time, or will the model render time displayed in the browser interface? In addition, what tools are used to implement the gzip compression model? What is the specific operation? @lilleyse

**Comment by lilleyse** [comment]
I just measured the total time it took to display the model after dragging it onto https://gltf-viewer.donmccurdy.com/. Not a super fine grained measurement so I don't have more exact numbers.

I used 7-zip to apply gzip compression. Just make sure that if you use gzip you need to tell your server to server the file as gzipped.

Is think this discussion is going beyond the scope of gltf-pipeline, but if you have more thoughts feel free to email me.

**Comment by jkfhto** [comment]
Thank you for your answer




------------------ 原始邮件 ------------------
发件人: "Sean Lilley"<notifications@github.com>;
发送时间: 2018年6月26日(星期二) 凌晨3:00
收件人: "AnalyticalGraphicsInc/gltf-pipeline"<gltf-pipeline@noreply.github.com>;
抄送: "qqq"<470778561@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AnalyticalGraphicsInc/gltf-pipeline] Decoding time is too long(#381)




I just measured the total time it took to display the model after dragging it onto https://gltf-viewer.donmccurdy.com/. Not a super fine grained measurement so I don't have more exact numbers.
 
I used 7-zip to apply gzip compression. Just make sure that if you use gzip you need to tell your server to server the file as gzipped.
 
Is think this discussion is going beyond the scope of gltf-pipeline, but if you have more thoughts feel free to email me.
