### ISSUE TITLE
Draco option having no effect

### ISSUE THREAD

**Issue by donmccurdy** [AnalyticalGraphicsInc/gltf-pipeline#420]
Using gltf-pipeline 2.0.0, and running:

```
gltf-pipeline -i chr_knight.gltf -o chr_knight_draco.gltf -d -s
```

No errors are printed, and the output file is valid, but output does not use the Draco extension. Original file (`chr_knight.gltf`) and output (`chr_knight_draco.gltf`) attached:

[chr_knight.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/2351193/chr_knight.zip)

**Comment by lilleyse** [comment]
Stepping through the code it looks like this is because the gltf doesn't have indices and `compressDracoMeshes` returns early if that's the case. This could be fixed by generating the indices on the fly and passing those through to `AddFacesToMesh`.

**Comment by donmccurdy** [comment]
Thanks! :)
