### ISSUE TITLE
为什么我运行是在控制台输出了gltf的信息，没有产生新的gltf文件。

### ISSUE THREAD

**Issue by liaoweiqi1997** [AnalyticalGraphicsInc/gltf-pipeline#425]
运行代码如下：gltf-pipeline -i model.gltf -o model2.gltf -d -s
效果如图：
![g5 tln 9c5 al yo5510 c](https://user-images.githubusercontent.com/31244684/45397639-91e50600-b673-11e8-986e-f9e219d4c253.png)

gltf-pipeline版本已经是2.0.0了

**Comment by lilleyse** [comment]
That's strange. I'm not sure why it would output to the screen like that.

A couple of questions:

What version of Node are you using?
Can you upload the model for us to test?

**Comment by liaoweiqi1997** [comment]
node版本为6.4.1.
模型为：
[model.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/2373415/model.zip)

**Comment by liaoweiqi1997** [comment]
我怀疑应该是gltf文件的原因
