### ISSUE TITLE
Embedded textures are lost  when converting to GLTF 2.0

### ISSUE THREAD

**Issue by DavidSkymap** [AnalyticalGraphicsInc/gltf-pipeline#428]
I have GLTF models that are in version 1.0. It uses embedded textures. I am using the gltf-pipeline Node library to process the GLTF models with the main goal to update the model to 2.0. 

I do nothing fancy. The code is just the following:
`return gltfPipeline.processGltf(gltf, {});`

If I try to load the model, the only thing I see is a black mesh block.
![image](https://user-images.githubusercontent.com/22907319/47169910-03644400-d305-11e8-9f90-be903a4e8c3c.png)

The 1.0 source and 2.0 result are here:
[GLTF_files.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/2492761/GLTF_files.zip)

Is this not supported, or is this a bug?

### Edit

Okay, sorry for jumping on conclusions. The operation seemed so straight forward, and there are no example on how a version upgrade is supposed to be executed. So I thought that I either had an issue in my file, or I was doing something wrong. But now I'm certain that this issue has to do with 'KHR_materials_common', or lack there of. 

It seems the current THREE js [loader](https://www.npmjs.com/package/three-gltf-loader) does not support this extension, and I am not informed enough to have a go at it myself (without a lot of invested time). As there lack an implementation of KHR_materials_common, how would one upgrade a version 1.0 to 2.0 using gltf-pipeline, and ignore or convert the KHR_materials_common? Or is there an alternative route? Or am I in the hands of invested THREE JS developers?

**Comment by donmccurdy** [comment]
I'm assuming this is your question? https://stackoverflow.com/questions/52888658/issues-in-threejs-with-converted-gltf-2-0-models/52897026. See response there for details.

However, I would be curious whether glTF-Pipeline can do the upgrade from KHR_materials_common (glTF 1.0) to metal/rough or spec/gloss PBR (glTF 2.0)? That should be much more straightforward than the GLSL conversions glTF-Pipeline already supports, for example.

**Comment by lilleyse** [comment]
Thanks for tracking down the issue @DavidSkymap and @donmccurdy. We have an issue open for the KHR_materials_common to PBR conversion already but haven't had a chance to look at it yet: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/384. But at least now we know there's some demand.

I'm going to close this and link from https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/384.
