### ISSUE TITLE
Combine primitives/nodes

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/gltf-pipeline#43]
@leerichard42 let's do this next.  It is a great performance optimization since it reduces the number of draw calls required at runtime and some exporters can generate really sub-optimal models. For example, I've seen the SketchUp export COLLADA where each triangle needed a separate draw call!  After running an optimization like this, the model only needed one draw call.

* [x] Stage to combine `primitives` in a node (if they have the same attribute formats, material, and mode; this will also require combining accessors/bufferviews/buffers)
* [x] Stage to combine `meshes` in a node
* [x] Stage to combine nodes (if they are not targeted for animation and have the same material), KhronosGroup/glTF#20

@tfili any additional advice here?

**Comment by tfili** [comment]
The only thing that was a bit of a pain was when meshes were used in multiple nodes with different transforms. When you combine those the mesh data needs to be duplicated because you will have to premultiply the transform before you combine them.

**Comment by pjcozzi** [comment]
@leerichard42 any update here?

**Comment by leerichard42** [comment]
Just checking, do you mean "combine primitives in a mesh"? Or can different meshes share common primitives?

**Comment by pjcozzi** [comment]
I mean if a mesh has an array of three primitives, for example, that those primitives would be combined into one primitive and the mesh would refer to that.

**Comment by leerichard42** [comment]
How should I deal with cases in which primitives share the same material/mode/attributes, but differ in properties in their accessors/bufferViews/buffers?
For example, if two similar primitives pointed to accessors with different types, or bufferViews with different targets, etc.
Right now, I have a check which does not merge the primitives if this happens, but I'm just wondering if certain cases should be handled in a different way?

**Comment by pjcozzi** [comment]
Can you provide a concrete example?  For example, if two primitives have the same attributes then the accessors will have the same format and we should be able to merge them.

**Comment by leerichard42** [comment]
I see, that answers my question - I wasn't sure if we were assuming that accessors for the same attribute would necessarily be in the same format.

However, I have a similar question about min/max values in accessors, such as in the following example from the boxAnimated sample model:
```
"accessors": {
    "accessor_31": {
        "bufferView": "bufferView_65",
        "byteOffset": 0,
        "byteStride": 12,
        "componentType": 5126,
        "count": 224,
        "max": [
            0.5,
            0.5,
            0.5
        ],
        "min": [
            -0.5,
            -0.5,
            -0.5
        ],
        "type": "VEC3"
    },
    "accessor_58": {
        "bufferView": "bufferView_65",
        "byteOffset": 7168,
        "byteStride": 12,
        "componentType": 5126,
        "count": 96,
        "max": [
            0.33504000306129456,
            0.5,
            0.33504000306129456
        ],
        "min": [
            -0.33504000306129456,
            -0.5,
            -0.33504000306129456
        ],
        "type": "VEC3"
    }
},
"primitives": [
    {
        "attributes": {
            "POSITION": "accessor_31"
        },
        "material": "Effect_outer",
        "mode": 4
    },
    {
        "attributes": {
            "POSITION": "accessor_58"
        },
        "material": "Effect_outer",
        "mode": 4
    }
]
```
In this example, the referenced accessors have different min/max values. Should I take the larger max and smaller min?

**Comment by pjcozzi** [comment]
>  I wasn't sure if we were assuming that accessors for the same attribute would necessarily be in the same format.

We should validate, for example, that two attributes named `POSITION` in two different primitives have accessors with the same `componentType`/`type` before batching, but they should in most practical cases.

**Comment by pjcozzi** [comment]
> In this example, the referenced accessors have different min/max values. Should I take the larger max and smaller min?

Yes, because we will end up with one accessor - and perhaps one bufferView/buffer - that combines the two.

**Comment by leerichard42** [comment]
I'm currently having this issue where I create new buffers using the old buffer/bufferViews, and the positions seem to be correct but the shading only happens based on the camera. I feel like this means that my new buffers cause the light position to be lost somewhere along the way, but I'm not sure. Do you know what might cause this issue? 
Correct shading:
![image](https://cloud.githubusercontent.com/assets/4475130/14768746/5c39bb5e-0a18-11e6-94f5-55cb367d255a.png)

Incorrect shading:
![image](https://cloud.githubusercontent.com/assets/4475130/14768748/7f5714ba-0a18-11e6-916a-f9f63409fce5.png)

**Comment by leerichard42** [comment]
Update: It turned out to be a problem I had with confusing the accessor and bufferView byte offsets, which meant that only the positions were actually correct.

**Comment by pjcozzi** [comment]
Glad you figured it out.

**Comment by leerichard42** [comment]
For two nodes to have the same material, does that just mean that all the primitives of all their meshes have the same material?

Also, what should the behavior be when combining nodes with the same material but different cameras/children/other properties?

**Comment by pjcozzi** [comment]
> For two nodes to have the same material, does that just mean that all the primitives of all their meshes have the same material?

Yes.  If the primitive/mesh combine is ran first, I believe the node should just have one mesh.  It would be fine to assume that.  Some users will just ask to "combine nodes" (which implies combining primitives/meshes) and others may ask to specifically just combine primitives and/or meshes so they can preserve the structure of the node hierarchy.

> Also, what should the behavior be when combining nodes with the same material but different cameras/children/other properties?

For children, I believe the strategy is to combine bottom up.  So, for example, if a node is targeted for animation, it can't be combined with siblings, but its entire sub-tree can be combined (assuming it meets the standard criteria).

As for cameras, I did not think about that.  Perhaps allow an option to combine when `camera` is defined, in which case the camera property (and, therefore, later in the pipeline, all camera properties) is removed.  This way users who don't care about cameras (Cesium as of now) can still get the full performance benefit and users that do care can preserve them.

As for the other node properties:
* `skeleton`, `skins`, `jointName` - we can consider in a separate PR if it makes it easier.  Just don't batch for now.
* `name` - this doesn't need to match but, of course, the node names will be lost when two nodes are combined.
* `extensions` - I have not thought about this.  I don't think any extensions extend a node yet.  To be safe, I think we should check if the `extension` object has known extensions and then merge if we can (right now, this would be no extensions) and warn if we can't.

**Comment by leerichard42** [comment]
Okay, sounds good. In terms of the children, should parents be able to combine with their children, allowing an entire chain to become one node, or should the merging only happen with siblings?

**Comment by pjcozzi** [comment]
>  In terms of the children, should parents be able to combine with their children, allowing an entire chain to become one node

Yes, exactly!  You should create several test scenarios, e.g., where
   * An entire tree is able to be combined
   * Just siblings can be combined
   * Two separate sub-trees can be combined, but the siblings (roots of these sub-trees) can't.

This is one of the most key optimization stages since some modeling tools will export very complex trees and, in many cases, the runtime doesn't care about differentiating individual nodes.

**Comment by leerichard42** [comment]
Actually, something I hadn't thought of earlier - why combined nodes need to share the same material? Couldn't we have combined nodes containing multiple meshes with different materials, giving us a smaller resulting tree?

**Comment by pjcozzi** [comment]
@leerichard42 that is a good idea, let's do it!  These nodes would still require multiple draw calls, of course (to change materials), but would have less overhead for applying transforms.

**Comment by pjcozzi** [comment]
This is being finished in #51.
