### ISSUE TITLE
GLTF to GLB convertion issue?

### ISSUE THREAD

**Issue by EtagiBI** [AnalyticalGraphicsInc/gltf-pipeline#435]
Hello,

I'm trying to convert my glTF to glb with separate textures and Draco compression. My command line is as follows:
`gltf-pipeline -i TestModel.gltf -o Converted/TestModel.glb -b -t -d -s`

As a result I get one glb file, one bin file and texture files. Is it an expected behavior? As far as I'm concerned, bin files are companions of glTF files, not glb. Is it a consequence of using "-t" for keeping textures links?

**Comment by lilleyse** [comment]
It's ok for a glb to have external bin files, though I guess it is a bit unusual. If you just want external textures but not external buffers, remove the `-s` flag from the command.

`gltf-pipeline -i TestModel.gltf -o Converted/TestModel.glb -t -d`

**Comment by EtagiBI** [comment]
> It's ok for a glb to have external bin files, though I guess it is a bit unusual.
I see. Is it a reliable combination then? Will it be supported in future versions of the format?

> If you just want external textures but not external buffers, remove the `-s` flag from the command.
Thanks for this tip!

**Comment by lilleyse** [comment]
@EtagiBI I believe it is.
