### ISSUE TITLE
about 2.0-cesium

### ISSUE THREAD

**Issue by verybigzhouhai** [AnalyticalGraphicsInc/gltf-pipeline#461]
I am having some problems when I use the 2.0-cesium branch.
I downloaded the 2.0-cesium branch. Based on the documentation, using the sample data, I executed the sample command and generated output.gltf. However, I can't load this gltf file properly in cesium1.54.
Is it where I am not doing right?

command：
node ./bin/gltf-pipeline.js -i ./specs/data/boxTexturedUnoptimized/CesiumTexturedBoxTest.gltf -o output.gltf --texcomp.dxt1.enable --texcomp.dxt1.quality=10 --texcomp.etc1.enable

thanks

**Comment by lilleyse** [comment]
I wouldn't recommend using the `2.0-cesium` branch, it is incomplete and only there for legacy purposes. It may be deleted at some point.

If you have a glTF 1.0 model and need to apply texture compression from the old gltf-pipeline you should use the `1.0` branch to do the initial conversion:

```
node ./bin/gltf-pipeline.js -i ./specs/data/boxTexturedUnoptimized/CesiumTexturedBoxTest.gltf -o output.gltf --texcomp.dxt1.enable --texcomp.dxt1.quality=10 --texcomp.etc1.enable
```

Followed by `master` to convert the model to glTF 2.0:

```
node ./bin/gltf-pipeline.js -i ./specs/data/boxTexturedUnoptimized/CesiumTexturedBoxTest.gltf -o output.gltf
```

But note that the texture compression capability is not standard glTF and at some point we may remove support for it in CesiumJS.

**Comment by verybigzhouhai** [comment]
@lilleyse
    My gltf version is 2.0, I would like to ask if the texture branch contains texture compression? I didn't find the relevant command, although it is not the standard gltf, but I am currently studying this texture compression.
So cesiumjs does not intend to continue to increase gltf 2.0 texture compression support in future versions?
thanks

**Comment by lilleyse** [comment]
@verybigzhouhai 

Only the `1.0` branch has texture compression. We developed it for glTF 1.0 but it was never standardized or widely used. I know some people are working on a proper compressed texture format that will get a glTF 2.0 extension. CesiumJS will support that once it's ready.

See https://www.khronos.org/assets/uploads/developers/library/2018-siggraph/02j-glTF-Compressed-Texture-Transmission-Format_Aug18.pdf for more details.

**Comment by verybigzhouhai** [comment]
@lilleyse
many texture maps, so I will continue to work on texture compression, I want to ask, all I need to do is upgrade the support for gltf to 2.0 is ok? Or there are some other places to pay attention to!

**Comment by verybigzhouhai** [comment]
@lilleyse
    I need to support these texture compressions in my program, because my model has too many texture maps, so I will continue to work on texture compression, I want to ask, all I need to do is upgrade the support for gltf to 2.0 is ok? Or there are some other places to pay attention to!

**Comment by verybigzhouhai** [comment]
@lilleyse

hi,Regarding the problem of gltf2.0 extended texture compression, I think that texture compression is very important on the mobile side, and it can get very obvious effects, so I added support and submitted the code,  hope to merge into the master branch.
thanks!

**Comment by verybigzhouhai** [comment]
Here are the solutions to this problem. https://github.com/verybigzhouhai/gltf-pipeline
