### ISSUE TITLE
Draco setting produces invalid file

### ISSUE THREAD

**Issue by artemzakharov** [AnalyticalGraphicsInc/gltf-pipeline#472]
When I compress a `.gltf` model with the Draco option and try to load the resulting file with three.js, I always get this error:

![image](https://user-images.githubusercontent.com/25446299/55847775-7e155b80-5aff-11e9-9271-44f0e6003ad9.png)

This is the file I used in this particular instance (opens fine in utilities like 3D viewer on Windows, so I don't think it's corrupted to begin with)
https://www.dropbox.com/s/kldnl21ney8jdaa/ElvenArcher.gltf?dl=0

This is the command I used to encode it:
`gltf-pipeline -i ElvenArcher.gltf -o ea-draco.gltf -d`

And this is how I try to load the result:
![image](https://user-images.githubusercontent.com/25446299/55847793-97b6a300-5aff-11e9-83f0-229bda2efb51.png)

Oddly enough, when I use Google's own Draco encoder (set up by following [this](https://codelabs.developers.google.com/codelabs/draco-3d/index.html#0) codelab) and encode the `.obj` file that the model was originally formatted as directly to draco code, the result is loaded by Three.js just fine. 

I've tried playing around with the encoding options, but I haven't been able to find any that produce a result that loads. I'm not 100% sure whether the fault is with the encoder or the three.js loader, but since the loader handles other Draco files fine, I figured I'd open an issue here first.

**Comment by artemzakharov** [comment]
After a little more investigation and taking note that the `gltf-pipeline` exported files explicitly in  `.gltf` format and _not_ `.drc` or anything like that, I decided to try using the three GLTF loader like this:
![image](https://user-images.githubusercontent.com/25446299/55850938-7360c380-5b0b-11e9-96a9-54de41ac83b9.png)

**Lo and behold, it works now!**

Being a newbie when it comes to .gltf and draco encoding, I don't even know what to make of this... it seems like there are two different Draco encoding standards:

Type 1:
- Exported by Google's compiled encoder
- Requires `loader = new THREE.DRACOLoader()`

Type 2: 
- Exported by `gltf-pipeline`
- Requires `loader = new THREE.GLTFLoader()` followed by `loader.setDRACOLoader(new THREE.DRACOLoader())`

Am I getting this right?

**Comment by lilleyse** [comment]
I think that's right. The draco content be loaded on its own as a .drc but can also be embedded in the glTF. The encoders are the same, it's just a matter of how the data is packaged.

**Comment by artemzakharov** [comment]
I'll go ahead and close the issue then, looks it was just a misunderstanding. Might be worth it to put a little disclaimer clarifying the difference between "pure" and "embedded" Draco content in the `readme` section that talks about the draco export option.
