### ISSUE TITLE
Compress gltf to draco seems not works

### ISSUE THREAD

**Issue by geremora** [AnalyticalGraphicsInc/gltf-pipeline#473]
[Archive.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/3064991/Archive.zip)

I tried compression draco with: gltf-pipeline -i model.gltf -o modelDraco.gltf -d

The process run well with the output: Total: 1648.635ms

But the final file has the same size of the original.

![Screen Shot 2019-04-10 at 1 14 09 PM](https://user-images.githubusercontent.com/2702584/55899367-9c786700-5b92-11e9-9049-0fe39e2abc15.png)

I'm attaching my model file.

Any ideas?

**Comment by lilleyse** [comment]
The textures are embedded into the glTF by default.

Try `gltf-pipeline -i model.gltf -o modelDraco.gltf -d -s` to save separate resources and you'll see the difference then.

**Comment by geremora** [comment]
That is a good point. Thanks @lilleyse 

![Screen Shot 2019-04-10 at 2 44 48 PM](https://user-images.githubusercontent.com/2702584/55905077-3ba35b80-5b9f-11e9-80ef-2b49dc8b6723.png)

Seems to working.
