### ISSUE TITLE
Draco does not appear to compress some models, including some Kronos sample models

### ISSUE THREAD

**Issue by creepytennis** [AnalyticalGraphicsInc/gltf-pipeline#484]
Hi,

I am having difficulty with Draco compression. I find that gltf-pipeline does not seem to apply any Draco compression using the -d switch (giving no error), on my own glTF file outputted from the THREE.js glTF exporter (probably my fault!), or on at least two of the Kronos glTF example files:

Avacado.glb does not seem to compress https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Avocado/glTF-Binary

BoomBox.glb does not seem to compress https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox/glTF-Binary

GearboxAssy.glb ** does compress ** https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/GearboxAssy/glTF-Binary

Perhaps you could use these examples as a clue as to what is preventing Draco from compressing some models? A debug message such as "Could not apply Draco because model ... " would also be really helpful! In particular I would really like to find out why my model will not compress, and fix it.

[alea.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/3276180/alea.zip)

Thanks,

Jamie

**Comment by lilleyse** [comment]
All those models get compressed when I try them. `alea.glb` goes from 2.6MB to 81.3KB.

Can you post the command you're using to run gltf-pipeline? The command I'm using is:

> node bin/gltf-pipeline.js -i alea.glb -o alea-draco.glb -d

**Comment by creepytennis** [comment]
Thanks for getting back to me. I have realised I made a very basic mistake with my npm upgrade and was mistakenly running an old version of gltf-pipeline (2.0). How embarrassing! Please accept my apologies & feel free to close or delete this issue. Thanks again. PS that is a great compression ratio! :)
