### ISSUE TITLE
uniform variables error after updating model from gltf v1.0 to gltf v2.0

### ISSUE THREAD

**Issue by liukangkanglkk99** [AnalyticalGraphicsInc/gltf-pipeline#488]
I am trying to update model from gltf v1.0 to gltf v2.0.
The following may occur in a gltf file: 
`"techniques":{
 "a":{
     "uniforms":{
         "u_tex":"tex",
         "u_tex2":"bakingTex"
     }
 },
 "b":{
     "uniforms":{
         "u_tex":"bakingTex"
     }
 }
}
`
But in the `function moveTechniquesToExtension(gltf)` of moveTechniquesToExtension.js, 
the mappedUniforms variable is finally recorded as bakingTex -> u_tex and bakingTex -> u_tex2 information is missing.
This leads to errors in later use of uniform u_tex2.

**Comment by lilleyse** [comment]
@liukangkanglkk99 Thanks for all the details, it should be quick for us to track this down. If you are able to share the glTF that would be helpful too.

**Comment by lilleyse** [comment]
@liukangkanglkk99 I opened a fix here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/490.

Would you mind trying it out with your gltf?

**Comment by liukangkanglkk99** [comment]
With pleasure. I tested this and it does work.
