### ISSUE TITLE
Draco compressed GLB not working with ARCore

### ISSUE THREAD

**Issue by karntrehan** [AnalyticalGraphicsInc/gltf-pipeline#505]
Hello there,
First of all great utility! Saved us a lot of time and helped us learn a lot.

We are facing an issue with the draco compressed object with ArCore. The uncompressed gltf and glb (https://poly.google.com/view/2w4Av7jJ2_B) work fine, but a draco compressed glb / gltf created using the pipeline leads to a crash on Android devices. 

To reproduce: https://github.com/pratish549/ArCore-Sample

**Comment by lilleyse** [comment]
Thanks @karntrehan!

Could you try loading another Draco model in ArCore to confirm whether it's gltf-pipeline issue or a general issue with ArCore? For example: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Draco

You could also try loading the model in another viewer like https://gltf-viewer.donmccurdy.com/

**Comment by karntrehan** [comment]
Hello @lilleyse , Thank you for the super quick response.

We replaced the url to that suggested by you, but the issue persists. You can view the change in this commit: https://github.com/pratish549/ArCore-Sample/commit/ae96bb2f5533e27da3ab1ce8e77c8a4bb4351782

Our hypothesis is the extension 'KHR_draco_mesh_compression" is not understood by ArCore. I think the same is being shown as a warning on https://gltf-viewer.donmccurdy.com/

Could this be a bug in the pipeline itself? Or will we need an additional layer on top of ArCore to decompress the draco object? We are trying to evaluate if this is a pipeline or an ArCore issue.

Thank you!

PS. The draco compressed GLBs do not function on ArKit as well.

**Comment by lilleyse** [comment]
@karntrehan I believe ArCore will need to decompress the draco object. The duck model I linked was not created with gltf-pipeline.

**Comment by karntrehan** [comment]
Thank you for the reply @lilleyse. I will explore ArCore further. 

Just for my knowledge, can you confirm the workflow of gltf-pipeline?
Is it taking my uncompressed `.gltf` file, applying draco on it to get a `.drc` file, and then re-converting the `.drc` file to a `.gltf`?

This will help me debug with ArCore.

**Comment by lilleyse** [comment]
gltf-pipeline does not generate an intermediary `.drc` but it does use the Draco JavaScript API to generate draco buffer views. For the full details see https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/compressDracoMeshes.js.

**Comment by karntrehan** [comment]
Thank you for the help @lilleyse ! Closing the issue and exploring other paths!
