### ISSUE TITLE
model is broken with draco.quantizePositionBits larger than 17

### ISSUE THREAD

**Issue by z1z2** [AnalyticalGraphicsInc/gltf-pipeline#511]
the model: [B.glb](https://github.com/z1z2/gltf/raw/master/B.glb)

the command line is 

`gltf-pipeline -i B.glb -d --draco.quantizePositionBits 18 -o B-18.glb`

original glb
![image](https://user-images.githubusercontent.com/7046470/71507374-459cf400-28bf-11ea-9562-8c59ab92af92.png)

converted glb
![image](https://user-images.githubusercontent.com/7046470/71507343-28682580-28bf-11ea-93fb-f96e3a4766a5.png)

**Comment by lilleyse** [comment]
@z1z2 I believe you're running into this CesiumJS bug: https://github.com/AnalyticalGraphicsInc/cesium/issues/7471.

I'm going to close this issue for now and keep track of it inside that issue.
