### ISSUE TITLE
don't combine buffers

### ISSUE THREAD

**Issue by haehn** [AnalyticalGraphicsInc/gltf-pipeline#513]
Hi there! When converting .gltf to .glb, all my different buffers are combined into a single one. Is there a way to prevent this from happening? Thank you!

**Comment by lilleyse** [comment]
I think it would require a change in the code.

Buffers are merged if their `mergedBufferName` is the same. Most of the time this name will be undefined and those buffers will be merged together. A way to fix it is set each one's `mergeBufferName` to a unique identifier when some command line option is passed in.

See https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/master/lib/mergeBuffers.js which is where the code change would probably go.

**Comment by emackey** [comment]
@haehn @lilleyse Sorry guys, GLB only supports a single embedded buffer (unlike "separate" glTF).  You can reference external buffers though.  I'm not entirely sure of the reasoning behind it.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#glb-stored-buffer

**Comment by lilleyse** [comment]
@emackey... ah of course, wasn't thinking about that. Though this issue could still be relevant to plain old glTF.

**Comment by haehn** [comment]
Ok thank you
