### ISSUE TITLE
Build currently breaks due to browserify

### ISSUE THREAD

**Issue by JoshuaStorm** [AnalyticalGraphicsInc/gltf-pipeline#54]
Build is currently based on browserify which seems to have issues with some of our code dependencies. @lasalvavida suggested it may be an issue he encountered where browserify can't handle dynamically loaded dependencies.
`    "build": "browserify index.js --standalone gltfPipeline -o build/gltf-pipeline.js",`

**Comment by pjcozzi** [comment]
Is this duplicate with #12?

Early on, this project supported browserify, but that is not a priority now.

**Comment by JoshuaStorm** [comment]
Yes it is. I seemed to have missed that somehow. Thanks!
