### ISSUE TITLE
Negative byteLength when using removeUnusedVertices

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#68]
Using a model that I ran through the obj2gltf converter, I'm seeing an issue where the `removeUnusedVertices` stage causes a buffer view to have a negative `byteLength` in the optimized gltf. This seemed to happen before #64 as well.

Here's the model I'm using:

[BoxTextured.txt](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/307849/BoxTextured.txt)

@lasalvavida can you investigate this?

**Comment by pjcozzi** [comment]
@lilleyse and all - please start labeling issues (for now just `bug` or `enhancement`) submitted to this repo.

**Comment by lasalvavida** [comment]
@lilleyse the provided model uses extras.source for shaders which gltf-pipeline still chokes on in writeSource. However, I can confirm that this failed on the BoxTextured model from the glTF sample models and currently works with #72.

**Comment by lilleyse** [comment]
Yeah https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/70 / https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/73 address the shader issue.
