### ISSUE TITLE
Handle transparent images

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#78]
The pipeline should be able to analyze an image to check if it has transparency, and if so edit the techniques for alpha blending. In the obj2gltf project I did a simple approach for this here: https://github.com/AnalyticalGraphicsInc/OBJ2GLTF/blob/master/lib/image.js. However there are also many pngs that have alpha channels but don't actually use them, so this approach wouldn't work.

**Comment by JoshuaStorm** [comment]
I am not quite sure I understand why transparent textures aren't handled properly, since it's just another texture. I'm assuming this has to be occurring in the write step since we don't do anything to the texture within the pipeline itself, do we?

**Comment by lilleyse** [comment]
The texture is mostly handled properly. The only aspect that isn't is when you actually export and view the model, it will look completely opaque, because the model won't know that it has to render as if it's transparent. So it has to enable alpha blending if a transparent texture is detected. Check out what the `modelMaterialCommon` does when `transparency` is set to below 1.0.

**Comment by lilleyse** [comment]
Also it doesn't have to happen in the write step, it could probably go in `addDefaults`.
