### ISSUE TITLE
removeUnusedVertices Removing Used Vertices

### ISSUE THREAD

**Issue by JoshuaStorm** [AnalyticalGraphicsInc/gltf-pipeline#83]
Testing the gltfPipeline with more involved models than the CesiumBox, I identified removeUnusedVertices seems to be removing all primitives except the main primitive of the model (is my terminology correct here? Still getting a feel for glTF). 

See attached images

gltfPipeline with removeUnusedVertices step
![removedprimitivesjpeg](https://cloud.githubusercontent.com/assets/12414183/16044380/321cd14a-3212-11e6-829e-ea55c2f5381c.jpg)

gltfPipeline without removeUnusedVertices
![notremovedjpg](https://cloud.githubusercontent.com/assets/12414183/16044451/75c853a6-3212-11e6-8028-65f17ac96cfe.jpg)

**Comment by lasalvavida** [comment]
@JoshuaStorm If you could attach the model files in a zip, it'll be easier for me to take a look at this.

**Comment by JoshuaStorm** [comment]
@lasalvavida 
Yep, sorry about that. See attached.

[removeUnusedIssue.zip](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/314092/removeUnusedIssue.zip)

**Comment by lasalvavida** [comment]
It looks like this is actually caused by combinePrimitives, still looking for a fix.

**Comment by lasalvavida** [comment]
It is not, the root cause of this needs to be found and corrected. The stages should be able to be run in any order (with dependencies of course) with no issue.
