### ISSUE TITLE
BrainStem sample model combinePrimitives throws exception

### ISSUE THREAD

**Issue by lasalvavida** [AnalyticalGraphicsInc/gltf-pipeline#85]
Probably related to #83

> buffer.js:835
>     throw new TypeError('value is out of bounds');
>     ^
> 
> TypeError: value is out of bounds
>     at checkInt (buffer.js:835:11)
>     at Buffer.writeUInt16LE (buffer.js:893:5)
>     at mergeAccessors (C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\combinePrimitives.js:233:36)
>     at combinePrimitiveGroup (C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\combinePrimitives.js:91:36)
>     at combineMeshPrimitives (C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\combinePrimitives.js:49:33)
>     at combinePrimitives (C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\combinePrimitives.js:19:43)
>     at processJSONWithExtras (C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\gltfPipeline.js:49:5)
>     at C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\gltfPipeline.js:63:9
>     at C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\readGltf.js:42:13
>     at C:\Users\rtaglang\AGI\git\gltf-pipeline\lib\loadGltfUris.js:18:9

**Comment by lasalvavida** [comment]
Pretty sure this happens because the BrainStem model has more than 65535 total vertices, so when combining, the index value exceeds the possible value.

combinePrimitives should be able to make multiple primitives to prevent this issue. I'll work on this once #88 gets merged.

**Comment by pjcozzi** [comment]
Let's also have a default option to use `OES_element_index_uint`, see https://github.com/KhronosGroup/glTF/pull/619.

**Comment by lasalvavida** [comment]
Closed by #162.
