### ISSUE TITLE
gltfPipeline.js not writing sources in all cases

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/gltf-pipeline#93]
When the output of `gltfPipeline.js` is JSON and not a file, the `extras._pipeline.source` are not written back to the glTF. We should call `writeSource` in `processFile` and `processJSON`.

@JoshuaStorm Do you want to look into this?

**Comment by JoshuaStorm** [comment]
Sure, I'll look into it now.

**Comment by lilleyse** [comment]
Fixed in #94
